# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!
#source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
#source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecsMirror.git'


platform :ios, '7.0'
	pod 'TYPagerController'
    pod 'Masonry', '~> 1.0.2'
    pod 'AMap3DMap', '~> 4.6.1'
    pod 'AMapSearch', '~> 4.5.0'
    pod 'AMapLocation', '~> 2.3.0'
    pod 'DateTools', '~> 2.0.0'
#    pod 'YYModel', '~> 1.0.4'
    pod 'YYKit', '~> 1.0.9'
target 'test' do

end

target 'test_effective' do
#    pod 'YYModel', '~> 1.0.4'
    pod 'QMUIKit', '~> 2.0.0'

end

#platform :ios, '8.0'
#pod 'Reveal-SDK', :configurations => ['Debug']
#end
