# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FFMpegForIOSDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   pod 'SDL-iOS-SDK', '~> 0.1.0'
   pod 'FFmpeg', '~> 2.8.3'

  # Pods for FFMpegForIOSDemo

  target 'FFMpegForIOSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FFMpegForIOSDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
