# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestMasory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	   pod 'Masonry', '~> 1.1.0'

  # Pods for TestMasory

  target 'TestMasoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestMasoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
