# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCoreText' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'DTCoreText', '~> 1.6.21'
   pod 'Masonry', '~> 1.1.0'
   pod "RACollectionViewReorderableTripletLayout"
   pod "BMDragCellCollectionView"
  # Pods for TestCoreText

  target 'TestCoreTextTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCoreTextUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
