# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioAttibute' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioAttibute
   pod 'AKSpeech', '~> 0.0.7'


end

target 'AVPlayerTEst' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AKSpeech', '~> 0.0.7'

  # Pods for AVPlayerTEst

end

target 'TestAudio' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestAudio

end

target 'TestAudio1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestAudio1

end
