# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCircleAk03' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Masonry', '~> 1.1.0'
   pod 'YYKit', '~> 1.0.9'
   pod 'IQKeyboardManager', '~> 3.3.7'

  # Pods for TestCircleAk03

  target 'TestCircleAk03Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCircleAk03UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
