# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'testAuroraIMUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for testAuroraIMUI
  pod 'AuroraIMUI', '~> 0.6.2'
  pod 'Aurora', '~> 1.0.0'

  
  target 'testAuroraIMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testAuroraIMUIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
