//
//  YDConstant.h
//  SportsBar
//
//  Created by 张旻可 on 15/11/5.
//  Copyright © 2015年 apple. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

FOUNDATION_EXPORT NSString *const YD_DB_NAME; //数据库name
FOUNDATION_EXPORT NSString *const YD_DB_IDENTIFIER; //数据库identifier

FOUNDATION_EXPORT NSString *const YDBAND_DB_NAME; //数据库name
FOUNDATION_EXPORT NSString *const YDBAND_DB_IDENTIFIER; //数据库identifier

FOUNDATION_EXPORT NSString *const YDPEDOMETER_DB_NAME; //数据库name
FOUNDATION_EXPORT NSString *const YDPEDOMETER_DB_IDENTIFIER; //数据库identifier

FOUNDATION_EXPORT NSString *const YDTREASURE_DB_NAME;//数据库name
FOUNDATION_EXPORT NSString *const YDTREASURE_DB_IDENTIFIER;//数据库identifier

FOUNDATION_EXPORT NSString *const YDFITNESS_DB_NAME; //数据库name
FOUNDATION_EXPORT NSString *const YDFITNESS_DB_IDENTIFIER; //数据库identifier

FOUNDATION_EXPORT NSString *const YDFITNESS_VIDEO_DB_NAME; //数据库name
FOUNDATION_EXPORT NSString *const YDFITNESS_VIDEO_DB_IDENTIFIER; //数据库identifier

FOUNDATION_EXPORT NSString *const YDDOWNLOAD_DB_NAME; //数据库name
FOUNDATION_EXPORT NSString *const YDDOWNLOAD_DB_IDENTIFIER; //数据库identifier

FOUNDATION_EXPORT NSString *const YDBodyFatScaleDbName;
FOUNDATION_EXPORT NSString *const YDBodyFatScaleDbIdentifier;

FOUNDATION_EXPORT NSString *const YDOPENHARDWARE_DB_NAME;
FOUNDATION_EXPORT NSString *const YDOPENHARDWARE_DB_IDENTIFIER;

FOUNDATION_EXPORT NSString *const YDFRIEND_DB_NAME;
FOUNDATION_EXPORT NSString *const YDFRIEND_DB_IDENTIFIER;

FOUNDATION_EXPORT NSString *const YDMESSAGECONTENT_DB_NAME;
FOUNDATION_EXPORT NSString *const YDMESSAGECONTENT_DB_IDENTIFIER;

FOUNDATION_EXPORT NSString *const YDFITNESS_VIDEO_COURSE_UPDATE_TAG_PREF;
FOUNDATION_EXPORT NSString *const YDFITNESS_VIDEO_COURSE_DETAIL_PREF;





FOUNDATION_EXPORT NSString *const GRADE_KEY; // 等级缓存
FOUNDATION_EXPORT NSString *const GRADE_SPE_TASKS_KEY; // 等级特殊任务缓存
FOUNDATION_EXPORT NSString *const APP_GRADE_PREFERENCE_NAME; // 等级缓存文件目录
FOUNDATION_EXPORT NSString *const APP_AIM_PREFERENCE_NAME; // 每日红包

FOUNDATION_EXPORT NSString *const YD_NEW_USER_ADDED_EVENT_KEY; //新用户上报事件已上报记录key


FOUNDATION_EXPORT NSString *const URL_SHORT_CUT_RUN_OUTDOOR;
FOUNDATION_EXPORT NSString *const URL_SHORT_CUT_RUN_INDOOR;
FOUNDATION_EXPORT NSString *const URL_SHORT_CUT_RIDE_BIKE;
FOUNDATION_EXPORT NSString *const URL_SHORT_CUT_FIT_INDEX;
FOUNDATION_EXPORT NSString *const URL_SHORT_CUT_STEP_TREASURE;
FOUNDATION_EXPORT NSString *const URL_SHORT_CUT_TAB_CHALLENGE;

FOUNDATION_EXPORT NSString *const APP_PREFERENCE_NAME; //应用级缓存
FOUNDATION_EXPORT NSString *const USER_PREFERENCE_NAME; //用户级缓存
FOUNDATION_EXPORT NSString *const USER_ME_VC_MODEL_PREFERENCE_NAME;
FOUNDATION_EXPORT NSString *const APP_AD_PREFERENCE_NAME;
FOUNDATION_EXPORT NSString *const USER_FITNESS_VIDEO_PRE_NAME;

FOUNDATION_EXPORT NSString *const APP_IS_LOGIN_KEY; //是否登录键
FOUNDATION_EXPORT NSString *const APP_USER_ID_KEY; //已登录的userIdKey

FOUNDATION_EXPORT NSString *const LAST_GOT_PD_TIME_KEY;
FOUNDATION_EXPORT NSString *const LAST_SEG_TOTAL_STEPS_KEY;

FOUNDATION_EXPORT NSString *const AUTO_STEP_UPDATE_T_KEY;
FOUNDATION_EXPORT NSString *const LAST_GET_SERVER_PD_TIME_KEY;

FOUNDATION_EXPORT NSString *const LAST_UPDATE_STEP_TIME_KEY;
FOUNDATION_EXPORT NSString *const LAST_STEPS_KEY;

FOUNDATION_EXPORT NSString *const LAST_ADD_LOCAL_PUSH_TIME_KEY;
FOUNDATION_EXPORT NSString *const APP_VERSION_KEY;

FOUNDATION_EXPORT NSString *const WAIT_UPLOAD_M7STEPS_ARR_KEY;
FOUNDATION_EXPORT NSString *const HUANXIN_PASSWORD_KEY;

FOUNDATION_EXPORT NSString *const ACCOUNT_KEY;
FOUNDATION_EXPORT NSString *const HUANXIN_USER_TYPE_KEY;
FOUNDATION_EXPORT NSString *const MEVC_MODEL_KEY;

FOUNDATION_EXPORT NSString *const WX_QR_CODE_KEY;
FOUNDATION_EXPORT NSString *const IS_WX_QR_CODE_AUTHORIZED_KEY;

FOUNDATION_EXPORT NSString *const BAND_STEP;
FOUNDATION_EXPORT NSString *const BAND_STEP_DATE;
FOUNDATION_EXPORT NSString *const BAND_UP_STEP;
FOUNDATION_EXPORT NSString *const BAND_UP_STEP_DATE;

FOUNDATION_EXPORT NSString *const BAND_STEP_DIC;
FOUNDATION_EXPORT NSString *const BAND_STEP_DATE_DIC;
FOUNDATION_EXPORT NSString *const BAND_UP_STEP_DIC;
FOUNDATION_EXPORT NSString *const BAND_UP_STEP_DATE_DIC;

FOUNDATION_EXPORT NSString *const TEST_USER_AUTO_REPORT_LOG_DATE;

/**
 * 用户偏好设置
 */
FOUNDATION_EXPORT NSString *const VOICE_BROADCAST_IS_ON_KEY;
FOUNDATION_EXPORT NSString *const AUTO_COUNTING_IS_ON_KEY;
FOUNDATION_EXPORT NSString *const USER_SHAKE_VOICE_ON_KEY;


/**
 * Facebook链接
 */
FOUNDATION_EXPORT NSString *const FACEBOOK_APP_URL;
FOUNDATION_EXPORT NSString *const FACEBOOK_APP_SHARE_URL;

/**
 * AD
 */
FOUNDATION_EXPORT NSString *const AD_INFOS_KEY;
FOUNDATION_EXPORT NSString *const AD_ICON_INFOS_KEY;
FOUNDATION_EXPORT NSString *const TOP_AD_ICON_INFOS_KEY;
FOUNDATION_EXPORT NSString *const AD_INDEX_KEY;
FOUNDATION_EXPORT NSString *const AD_INTERVAL_KEY;
FOUNDATION_EXPORT NSString *const AD_LAST_SHOW_TIME_KEY;

FOUNDATION_EXPORT NSString *const AD_SDK_OPEND;
FOUNDATION_EXPORT NSString *const AD_SDK_SWITCH;
FOUNDATION_EXPORT NSString *const AD_SDK_SEC;

/**
 *  每日红包
 */
FOUNDATION_EXPORT NSString *const DAILY_AIM_REWARD_DIC_KEY;
FOUNDATION_EXPORT NSString *const DAILY_AIM_REWARD_DRAW_TIME;
FOUNDATION_EXPORT NSString *const DAILY_AIM_CAN_DRAW_REWARD_TIME;

/**
 *  分享红包
 */
FOUNDATION_EXPORT NSString *const LAST_DRAW_SHARE_REWARD_TIME;

/**
 *  记步存取方式更新key
 */
FOUNDATION_EXPORT NSString *const STEPS_PREFERENCE_UPDATE_KEY;

/**
 *  QQ运动红包奖励url key
 */
FOUNDATION_EXPORT NSString *const QQ_SPORT_REWARD_URL_KEY;



/**
 *  webview
 */
FOUNDATION_EXPORT NSString *const WEB_OPEN_ON_SELF_KEY;
FOUNDATION_EXPORT NSString *const WEB_BACK_TO_PREV_KEY;
FOUNDATION_EXPORT NSString *const WEB_BACK_TO_REFRESH_KEY;
FOUNDATION_EXPORT NSString *const WEB_SHOW_SHARE_KEY;
FOUNDATION_EXPORT NSString *const WEB_CAN_PULL_REFRESH_KEY;
FOUNDATION_EXPORT NSString *const WEB_BACK_TO_REFRESH_FUNC;
FOUNDATION_EXPORT NSString *const WEB_BACK_TO_URL_FUNC;
FOUNDATION_EXPORT NSString *const WEB_NETWORK_STATUS_CHANGE_FUNC;

/**
 *  notification
 */
FOUNDATION_EXPORT NSString *const NTF_APP_ORIENTATION_WILL_CHANGE;
FOUNDATION_EXPORT NSString *const NTF_APP_ORIENTATION_DID_CHANGED;

FOUNDATION_EXPORT NSString *const NTF_MGR_VIDEO_PLAY_OVER;
FOUNDATION_EXPORT NSString *const NTF_MGR_VIDEO_PLAY_FAIL;
FOUNDATION_EXPORT NSString *const NTF_MGR_AUDEO_PLAY_OVER;

FOUNDATION_EXPORT NSString *const NTF_HARDWARE_WEIGHT_DATA_UPDATE;

/*
 *  app id
 */
FOUNDATION_EXPORT NSString *const APP_ID_TALKING_DATA;

// UI
//UIKIT_EXTERN CGFloat const YDAchievementHeaderH;
//UIKIT_EXTERN CGFloat const YDAchievementFooterH;


FOUNDATION_EXPORT NSString *const OFFLINE_DOWNLOADCLICKED_ITEM;
FOUNDATION_EXPORT NSString *const MGR_OFFLINE_DOWNLOADED_ITEM;
FOUNDATION_EXPORT NSString *const MGR_OFFLINE_DOWNLOADING_ITEM;
FOUNDATION_EXPORT NSString *const MGR_OFFLINE_DELETE_ITEM;

// bg image
FOUNDATION_EXPORT NSString *const ydNtfIndexBgImageUpdate;
FOUNDATION_EXPORT NSString *const ydNtfReloadCollectionView;

