# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testPhoto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 pod 'Masonry', '~> 1.1.0'
  # Pods for testPhoto
   pod 'TZImagePickerController', '~> 1.9.6'

  target 'testPhotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testPhotoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
