# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YDProgressView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'MRProgress', '~> 0.8.3'
 pod 'Masonry', '~> 1.0.2'
 pod 'YYImage', '~> 1.0.4'
 pod 'YYWebImage'
pod 'AFNetworking', '~> 3.1.0'

  # Pods for YDProgressView

#  target 'YDProgressViewTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'YDProgressViewUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
