# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPureLayout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for TestPureLayout
   pod 'PureLayout', '~> 3.0.2'

  target 'TestPureLayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestPureLayoutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
