# Uncomment the next line to define a global platform for your project
 platform :ios, '7.0'

#target 'BabyBluetoothAppDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BabyBluetoothAppDemo
    pod 'BabyBluetooth', '~> 0.7.0'
    pod 'SVProgressHUD', '~> 2.1.2'


target 'BabyBluetoothAppDemo' do

end

target 'MyselfDemo' do
    
end
