
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestProject

  target 'TestProjectTests' do
    inherit! :search_paths
    # Pods for testing
	   pod 'Masonry', '~> 1.1.0'
  end

  target 'TestProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
