# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YY' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YY
  pod 'YYImage', '~> 1.0.4'

  target 'YYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
